export const ACTIONS = {
  ADD_TO_BASKET: 'ADD_TO_BASKET', // TODO: DELETE ME
  INCREMENT_ITEM: 'INCREMENT_ITEM', // TODO: DELETE ME
  DECREMENT_ITEM: 'DECREMENT_ITEM', // TODO: DELETE ME
  GET_FROM_LOCAL_STATE: 'GET_FROM_LOCAL_STATE', // TODO: DELETE ME
  ADD_TRANSACTION: 'ADD_TRANSACTION',
  ADD_TRANSACTIONS: 'ADD_TRANSACTIONS',
};

export default ACTIONS;
